blank_issues_enabled: true
contact_links:
  - name: How to contribute
    url: https://github.com/spencerboggs/independent-games-db/blob/main/CONTRIBUTING.md
    about: Read this before opening a pull request.
